# Generated by Django 6.0.2 on 2026-02-22 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_points', models.IntegerField(default=10000)),
                ('remaining_points', models.IntegerField(default=10000)),
                ('players_needed', models.IntegerField(default=11)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('BAT', 'BAT'), ('BOWL', 'BOWL'), ('AR', 'AR'), ('PLY', 'PLY')], max_length=10)),
                ('base_price', models.IntegerField()),
                ('sold_price', models.IntegerField(blank=True, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricket.team')),
            ],
        ),
    ]
