# Generated by Django 6.0.2 on 2026-02-24 20:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('BAT', 'Batting Icon'), ('BOWL', 'Bowling Icon'), ('AR', 'All Rounder Icon'), ('PLY', 'Player')], max_length=10)),
                ('base_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sold_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('UNSOLD', 'Unsold'), ('SOLD', 'Sold'), ('NOT_PLAYING', 'Not Playing'), ('FREE', 'Free Addition')], default='UNSOLD', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='player_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='JerseyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_on_jersey', models.CharField(max_length=200)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('size_number', models.IntegerField(blank=True, null=True)),
                ('size_text', models.CharField(blank=True, max_length=10, null=True)),
                ('sponsor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cricket.player')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_started', models.BooleanField(default=False)),
                ('current_stage', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('BAT', 'Batting Icons'), ('BOWL', 'Bowling Icons'), ('AR', 'All Rounder Icons'), ('OPEN', 'Open Auction'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('is_rebid', models.BooleanField(default=False)),
                ('is_parked', models.BooleanField(default=False)),
                ('size_mapping', models.JSONField(blank=True, default=dict)),
                ('current_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricket.player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('total_points', models.IntegerField(default=10000)),
                ('remaining_points', models.IntegerField(default=10000)),
                ('max_players', models.IntegerField(default=15)),
                ('auction_slots', models.IntegerField(default=11)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='cricket_tea_name_42d4dc_idx')],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricket.team'),
        ),
        migrations.CreateModel(
            name='AuctionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('SOLD', 'Sold'), ('UNSOLD', 'Unsold'), ('NOT_PLAYING', 'Not Playing'), ('STAGE_CHANGE', 'Stage Change'), ('UNDO', 'Undo'), ('MANUAL_EDIT', 'Manual Edit')], max_length=20)),
                ('sold_price', models.IntegerField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricket.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricket.team')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['role'], name='cricket_pla_role_91c8d8_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['status'], name='cricket_pla_status_f5d66d_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['serial_number'], name='cricket_pla_serial__fea4b4_idx'),
        ),
    ]
