# Generated by Django 6.0.2 on 2026-02-22 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mobile_number',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must be exactly 10 digits.', regex='^\\d{10}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='place',
            field=models.CharField(default='1234567890', max_length=100),
            preserve_default=False,
        ),
    ]
