# Generated by Django 6.0.2 on 2026-02-23 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_player_mobile_number_player_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='base_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='sold_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
