# Generated by Django 6.0.2 on 2026-02-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0003_alter_player_base_price_alter_player_sold_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='max_players',
            field=models.IntegerField(default=15),
        ),
    ]
