# Generated by Django 6.0.3 on 2026-03-07 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('role', models.CharField(choices=[('BAT', 'BAT'), ('BOWL', 'BOWL'), ('AR', 'AR'), ('PLY', 'PLY')], max_length=10)),
                ('base_price', models.IntegerField(default=0)),
                ('sold_price', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='AVAILABLE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('owners', models.CharField(blank=True, max_length=200)),
                ('payment_info', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('remaining_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField()),
                ('bidding_slots', models.IntegerField()),
                ('max_squad_size', models.IntegerField()),
                ('base_price_AR', models.IntegerField()),
                ('base_price_BAT', models.IntegerField()),
                ('base_price_BOWL', models.IntegerField()),
                ('base_price_PLY', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jersey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_name', models.CharField(max_length=100)),
                ('jersey_number', models.IntegerField()),
                ('size_number', models.IntegerField()),
                ('size_text', models.CharField(max_length=10)),
                ('sponsor', models.CharField(blank=True, max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.team'),
        ),
        migrations.CreateModel(
            name='AuctionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SELL', 'SELL'), ('UNSOLD', 'UNSOLD'), ('NOT_PLAYING', 'NOT_PLAYING'), ('UNDO', 'UNDO')], max_length=20)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('round', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.team')),
            ],
        ),
    ]
