# Generated by Django 6.0.3 on 2026-03-13 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('role', models.CharField(choices=[('BAT', 'BAT'), ('BOWL', 'BOWL'), ('AR', 'AR'), ('PLY', 'PLY')], max_length=10)),
                ('base_price', models.IntegerField(default=0)),
                ('sold_price', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold'), ('UNSOLD', 'Unsold'), ('NOT_PLAYING', 'Not Playing')], default='AVAILABLE', max_length=20)),
                ('rebid_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, help_text='Abbreviation shown on auction buttons e.g. MI, RCB', max_length=20)),
                ('owners', models.CharField(blank=True, max_length=200)),
                ('payment_info', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('remaining_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=10000)),
                ('bidding_slots', models.IntegerField(default=11)),
                ('max_squad_size', models.IntegerField(default=13)),
                ('base_price_AR', models.IntegerField(default=1000)),
                ('base_price_BAT', models.IntegerField(default=400)),
                ('base_price_BOWL', models.IntegerField(default=400)),
                ('base_price_PLY', models.IntegerField(default=100)),
                ('category_order', models.CharField(default='AR,BAT,BOWL,PLY', max_length=50)),
                ('max_rebid_attempts', models.IntegerField(default=3)),
                ('size_mapping', models.TextField(default='{"36":"XS","38":"S","40":"M","42":"L","44":"XL","46":"XXL"}', help_text='JSON mapping of size number to size label e.g. {"38":"M"}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(default='KPL Auction', help_text='Shown on public board and all pages', max_length=100)),
                ('auction_date', models.DateTimeField(blank=True, null=True)),
                ('match_date', models.DateTimeField(blank=True, null=True)),
                ('banner_path', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Tournament Settings',
            },
        ),
        migrations.CreateModel(
            name='Jersey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_name', models.CharField(max_length=100)),
                ('jersey_number', models.IntegerField()),
                ('size_number', models.IntegerField()),
                ('size_text', models.CharField(max_length=10)),
                ('sponsor', models.CharField(blank=True, max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.player')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('MAIN', 'Main Round'), ('REBID', 'Rebid Round'), ('DONE', 'Auction Complete')], default='MAIN', max_length=10)),
                ('current_category', models.CharField(default='AR', max_length=10)),
                ('category_pass', models.IntegerField(default=1)),
                ('auction_round', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awaiting_transition', models.BooleanField(default=False)),
                ('transition_message', models.CharField(blank=True, max_length=200)),
                ('current_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_state', to='auction.player')),
            ],
            options={
                'verbose_name': 'Auction State',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.team'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
                ('round_label', models.CharField(default='League', help_text='e.g. League, Quarter-Final, Semi-Final, Final', max_length=50)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='auction.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='auction.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='auction.team')),
            ],
            options={
                'ordering': ['match_number'],
            },
        ),
        migrations.CreateModel(
            name='ExtraJerseyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role_label', models.CharField(blank=True, help_text='e.g. Manager, Coach, Volunteer', max_length=50)),
                ('jersey_name', models.CharField(blank=True, max_length=100)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('member_type', models.CharField(choices=[('TEAM', 'Team Extra'), ('ORGANISER', 'Organiser')], default='TEAM', max_length=20)),
                ('group_name', models.CharField(blank=True, default='Organisers', max_length=100)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_members', to='auction.team')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SELL', 'SELL'), ('UNSOLD', 'UNSOLD'), ('NOT_PLAYING', 'NOT_PLAYING'), ('UNDO', 'UNDO')], max_length=20)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('round', models.IntegerField(default=1)),
                ('category', models.CharField(blank=True, max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.team')),
            ],
        ),
    ]
